### ISSUE TITLE
The generated command to run tests on Typescript is wrong

### ISSUE THREAD

**Issue by webNeat** [japa/create-japa#1] opened 2023-08-13 15:54 UTC
### Package version

1.2.0

### Describe the bug

When running `npm init japa@latest` and choosing `Typescript` or `Typescript ESM`, at the end of the setup these lines are printed:

```
✔ Configured japa successfully
❯ Run "node bin/test.ts" to execute tests
```

if the user directly runs the command `node bin/test.ts` it will give them an error. They will have to go search in the docs how to correctly run tests with Typescript ...

**Comment by vincent-vade** [comment] 2023-10-19 08:05
Hello,

Same here ! I've been created a fresh install of japa with typescript. I added expect as assertion library
But the type of TestContext it's not resolve as expected.

It's possible to fix this issue ?

As a can see the PR linked is out of date.

Best regards

**Comment by Julien-R44** [comment] 2023-10-19 08:39
Hey @vincent-vade, can you give more info or give a reproduction repo? 

This issue was about Japa 2. The problem has been solved with Japa 3. In any case, I've just tried it and I've had no problems, Testcontext and Expect are correctly typed.

**Comment by vincent-vade** [comment] 2023-10-19 08:49
@Julien-R44 thank for you're reply...

I'm actually on monorepo with turborepo

so i can share some file

Node version: v20.5.1
Turborepo: latest

```
// apps/my-app/package.json
// Package.json
  "scripts": {
    "test": "node --loader ts-node/esm --enable-source-maps bin/test.ts"
   },
  "devDependencies": {
    "@japa/api-client": "^2.0.0-1",
    "@japa/expect": "^3.0.0",
    "@japa/runner": "^3.0.0-9",
    "@types/node": "^20.8.2",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
  ```
  
  ``` dummy test
// app/my-app/tests/math.spec.ts
import { test } from "@japa/runner";

test.group("Maths.add", () => {
    test("add two numbers", ({ expect }) => {
      // Test logic goes here
      expect(1 + 1).toBe(2);
    });
});
  ```

```
// japa config
import { configure, processCLIArgs, run } from '@japa/runner'
import { expect } from '@japa/expect'
import { apiClient } from '@japa/api-client'

processCLIArgs(process.argv.splice(2))
configure({
  files: ['tests/**/*.spec.ts'],
  plugins: [expect(), apiClient('http://localhost:3333')],
})

run()
```

And i've try to debug, so as i understand the type definitions from @japa/expect doesn't work

```
// the error is from here => '@japa/runner/core' does not exist
// error from typescript
// TS2664: Invalid module name in augmentation, module  @japa/runner/core  cannot be found.
declare module '@japa/runner/core' {
  interface TestContext {
    expect: Expect
  }
}
```
 
 If you want more tell me :)

Best regards

Vincent

**Comment by Julien-R44** [comment] 2023-10-19 17:33
well, i would say it's probably something caused by turborepo and the way it handles packages, since it works totally fine with a "simple" repo. If it's possible for you to create a minimal reproduction repo with turborepo, i would be happy to take a look !

what package manager are you using?

**Comment by Julien-R44** [comment] 2023-10-27 19:09
Closing since original issue has been fixed

@vincent-vade Feel free to open another issue for that ( perhaps with a reproduction ? ). To me, it looks like a different issue.

**Closed as completed by Julien-R44** 2023-10-27 19:09 UTC
